"""License whitelist and ATTRIBUTION.md generation."""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable

# Canonical forms we accept. Anything fetched/dropped must normalise to one of these.
DEFAULT_WHITELIST = ("CC0", "PDM", "CC-BY-4.0", "CC-BY-SA-4.0")

_LICENSE_PATTERNS = [
    (re.compile(r"^\s*cc0(\s|-|_)?(1\.0)?\s*$", re.I), "CC0"),
    (re.compile(r"creativecommons\.org/publicdomain/zero", re.I), "CC0"),
    (re.compile(r"^\s*pdm(\s|-|_)?(1\.0)?\s*$", re.I), "PDM"),
    (re.compile(r"creativecommons\.org/publicdomain/mark", re.I), "PDM"),
    (re.compile(r"public[-\s_]?domain", re.I), "PDM"),
    (re.compile(r"^\s*cc[-\s_]?by[-\s_]?sa[-\s_]?4\.0", re.I), "CC-BY-SA-4.0"),
    (re.compile(r"creativecommons\.org/licenses/by-sa/4\.0", re.I), "CC-BY-SA-4.0"),
    (re.compile(r"^\s*cc[-\s_]?by[-\s_]?4\.0", re.I), "CC-BY-4.0"),
    (re.compile(r"creativecommons\.org/licenses/by/4\.0", re.I), "CC-BY-4.0"),
]

# Hard rejects: ND forbids derivative works (mixing IS a derivative); NC is fine
# for a personal play-at-home MP3 but we keep things conservative and reject it
# so the pipeline stays redistributable in principle.
_REJECT_PATTERNS = [
    (re.compile(r"\bnd\b", re.I), "no-derivatives (ND) licenses forbid mixing"),
    (re.compile(r"-nd-", re.I), "no-derivatives (ND) licenses forbid mixing"),
    (re.compile(r"\bnc\b", re.I), "non-commercial (NC) licenses excluded by policy"),
    (re.compile(r"-nc-", re.I), "non-commercial (NC) licenses excluded by policy"),
]


def normalise(raw: str) -> str | None:
    """Map a free-text license string to a canonical form, or None."""
    if not raw:
        return None
    for pat, reason in _REJECT_PATTERNS:
        if pat.search(raw):
            return None
    for pat, canonical in _LICENSE_PATTERNS:
        if pat.search(raw):
            return canonical
    return None


class LicenseError(RuntimeError):
    pass


def assert_allowed(raw: str, whitelist: Iterable[str], context: str) -> str:
    canonical = normalise(raw)
    if canonical is None:
        raise LicenseError(
            f"{context}: license {raw!r} is not recognised or is explicitly excluded"
        )
    if canonical not in set(whitelist):
        raise LicenseError(
            f"{context}: license {canonical} not in whitelist {sorted(set(whitelist))}"
        )
    return canonical


def write_attribution(manifest_path: Path, attribution_path: Path) -> None:
    manifest = json.loads(manifest_path.read_text())
    by_layer: dict[str, list[dict]] = {}
    for entry in manifest.get("assets", []):
        by_layer.setdefault(entry.get("layer", "other"), []).append(entry)

    lines: list[str] = []
    lines.append("# Attribution")
    lines.append("")
    lines.append(
        "This file is generated by `birdsong_mix` from `manifest.json`. "
        "Every source file used in the build is listed below with its "
        "author, license and origin URL."
    )
    lines.append("")
    for layer in sorted(by_layer):
        lines.append(f"## {layer}")
        lines.append("")
        for entry in sorted(by_layer[layer], key=lambda e: e.get("filename", "")):
            fn = entry.get("filename", "?")
            author = entry.get("author") or "unknown"
            lic = entry.get("license", "?")
            url = entry.get("source_url") or ""
            url_part = f" — <{url}>" if url else ""
            lines.append(f"- **{fn}** — {author} — {lic}{url_part}")
        lines.append("")
    attribution_path.write_text("\n".join(lines))
